name: example
description: A sample command-line application as an example for kiwi.
version: 0.1.0
homepage: https://github.com/vanlooverenkoen/kiwi

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  kiwi: ^4.0.3

dev_dependencies:
  test: ^1.21.1
  build_runner: ^2.1.11
  kiwi_generator: ^4.0.3

dependency_overrides:
  kiwi:
    path: ../kiwi
  kiwi_generator:
    path: ../kiwi_generator