name: kiwi
description: A simple yet efficient dependency injection container for Dart and Flutter (can be coupled with the kiwi_generator package).
version: 4.0.3
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.1
